name: Trivy Scan and Upload SARIF Report
description: Scan the Docker image with Trivy and upload the SARIF report to GitHub

inputs:
  python-version:
    description: The Python version to use
    required: true
  docker-username:
    description: The Docker username to use
    required: true
  docker-password:
    description: The Docker password to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.docker-username }}/hello-flask:py${{ inputs.python-version }}
        format: "sarif"
        output: "trivy-report-${{ inputs.python-version }}.sarif"

    - name: Upload Trivy report
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: "trivy-report-${{ inputs.python-version }}.sarif"