name: Build and Test
description: Build and test the application

inputs:
  python-version:
    description: The Python version to use
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest test_app.py -v

    - name: Manual Endpoint Testing
      run: |
        python app.py &
        sleep 10
        curl -f http://localhost:8000
        curl -f http://localhost:8000/health
        curl -f http://localhost:8000/api/info
        curl -f http://localhost:8000/api/multiply/2/3
        pkill -f "python app.py"