name: CI with Matrix Strategy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false # continue running tests even if some fail.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest test_app.py -v

      - name: Test App Manually
        run: |
          python app.py &
          sleep 10
          curl -f http://localhost:8000
          curl -f http://localhost:8000/health
          curl -f http://localhost:8000/api/info
          curl -f http://localhost:8000/api/multiply/2/3
          pkill -f "python app.py"

  build:
        needs: test
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.11", "3.12"]

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build Docker image for Python ${{ matrix.python-version }}
          uses: docker/build-push-action@v5
          with:
            context: .
            build-args: PYTHON_VERSION=${{ matrix.python-version }}
            tags: hello-flask:${{ matrix.python-version }}
            push: false
            load: true
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Test Docker Container
          run: |
            docker run -d --name test-container-${{ matrix.python-version }} \
                      -p 800${{ strategy.job-index}}:8000 \
                      -e PYTHON_VERSION=${{ matrix.python-version }} \
                      hello-flask:${{ matrix.python-version }}
            sleep 10
            curl -f http://localhost:800${{ strategy.job-index }}/health
            curl -f http://localhost:800${{ strategy.job-index }}/api/info

        - name: Stop container
          run: |
            docker stop test-container-${{ matrix.python-version }}
            docker rm test-container-${{ matrix.python-version }}

  security-scan:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: hello-flask:${{ matrix.python-version }}
          format: "sarif"
          output: "trivy-report-${{ matrix.python-version }}.sarif"

      - name: Upload Trivy report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-report-${{ matrix.python-version }}.sarif"

  # Deploy the application to the specified environment
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["staging", "production"]
    environment: ${{ matrix.environment }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Environment
        run: |
          echo "Deploying to ${{ matrix.environment }} environment"

      # Simulating deployment
      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deployed to ${{ matrix.environment }} environment successfully"
