name: Continuous Integration Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11", "3.12"]
            fail-fast: false # continue running tests even if some fail.
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-and-test
              with:
                python-version: ${{ matrix.python-version }}

    build:
        needs: test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11", "3.12"]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/docker-build-push
              with:
                python-version: ${{ matrix.python-version }}

    security-scan:
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11", "3.12"]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/trivy-scan-upload
              with:
                python-version: ${{ matrix.python-version }}
